version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    # networks:
    #   - polar

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./data/redis:/data
    # networks:
    #   - polar

  server:
    env_file:
      - apps/server/.env.development
    volumes:
      - ./apps/server/src:/usr/src/app/apps/server/src
      # - /user/src/app/node_modules
    container_name: server
    restart: unless-stopped
    ports:
      - '${APP_PORT}:${APP_PORT}'
    expose:
      - ${APP_PORT}
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - postgres
      - redis
    # networks:
    #   - polar


networks:
  polar:
    external:
      name: 1_default
